//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OP3.Presentacion.WcfServicios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTOUsuario", Namespace="http://schemas.datacontract.org/2004/07/WcfServicios")]
    [System.SerializableAttribute()]
    public partial class DTOUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServicios.IWfServicios")]
    public interface IWfServicios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfServicios/ObtenerUsuario", ReplyAction="http://tempuri.org/IWfServicios/ObtenerUsuarioResponse")]
        OP3.Presentacion.WcfServicios.DTOUsuario ObtenerUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfServicios/ObtenerUsuario", ReplyAction="http://tempuri.org/IWfServicios/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<OP3.Presentacion.WcfServicios.DTOUsuario> ObtenerUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfServicios/GetTodosLosUsuarios", ReplyAction="http://tempuri.org/IWfServicios/GetTodosLosUsuariosResponse")]
        OP3.Presentacion.WcfServicios.DTOUsuario[] GetTodosLosUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWfServicios/GetTodosLosUsuarios", ReplyAction="http://tempuri.org/IWfServicios/GetTodosLosUsuariosResponse")]
        System.Threading.Tasks.Task<OP3.Presentacion.WcfServicios.DTOUsuario[]> GetTodosLosUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWfServiciosChannel : OP3.Presentacion.WcfServicios.IWfServicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WfServiciosClient : System.ServiceModel.ClientBase<OP3.Presentacion.WcfServicios.IWfServicios>, OP3.Presentacion.WcfServicios.IWfServicios {
        
        public WfServiciosClient() {
        }
        
        public WfServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WfServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WfServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WfServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OP3.Presentacion.WcfServicios.DTOUsuario ObtenerUsuario(int id) {
            return base.Channel.ObtenerUsuario(id);
        }
        
        public System.Threading.Tasks.Task<OP3.Presentacion.WcfServicios.DTOUsuario> ObtenerUsuarioAsync(int id) {
            return base.Channel.ObtenerUsuarioAsync(id);
        }
        
        public OP3.Presentacion.WcfServicios.DTOUsuario[] GetTodosLosUsuarios() {
            return base.Channel.GetTodosLosUsuarios();
        }
        
        public System.Threading.Tasks.Task<OP3.Presentacion.WcfServicios.DTOUsuario[]> GetTodosLosUsuariosAsync() {
            return base.Channel.GetTodosLosUsuariosAsync();
        }
    }
}
